M48
; DRILL file {KiCad 9.0.0} date 2025-05-27T01:05:00-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-27T01:05:00-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C3.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C4.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T7C8.400
%
G90
G05
T1
X142.975Y-80.85
T2
X124.5Y-58.5
T3
X75.8Y-61.6
X75.8Y-68.6
T4
X65.75Y-84.5
X65.75Y-115.5
X100.0Y-95.4
X134.25Y-84.5
X134.25Y-115.5
T5
X90.0Y-90.0
X110.0Y-89.93
T6
X58.75Y-58.75
X58.75Y-141.25
X141.25Y-58.75
X141.25Y-141.25
T7
X90.0Y-90.0
X110.0Y-90.0
M30
